#!/bin/bash

# This script is used to keep accessible the shared `apuntes` directory inside
# the chroot jail.
#
# This is intended to be used as root by a cronjob. The "proper" way to do it
# is using fstab to mount it on startup, but I'd prefer not to do that because
# editing the fstab file automatically is, at least, dangerous, and it has to
# be edited every time a user is registered.
#
# Anyway, this also cleans up any home dir of any user that couldn't be deleted
# manually.
#
# Also, this now takes care of processing with jekill the static sites if
# needed.
USERS=$(cat /etc/group |                     \
          grep -e '^\(teachers\|alumns\):' | \
          cut -d : -f 4 |                    \
          tr , " " | tr '\n' " ")

echo "Starting maintenance routine at $(date)"

for user in $USERS; do
  home=$(cat /etc/passwd |                   \
           grep -e "^$user:" |               \
           cut -d : -f 6 |                   \
           grep -e '^/home')
  if [ "x$home" != "x" ]; then
    # Try to rmdir, if it failed either it didn't exist or wasn't empty (either
    # already mounted or with other contents).
    rmdir "$home/apuntes" > /dev/null 2>&1
    if [ $? -eq 0 ]; then
      mkdir "$home/apuntes"
      mount --bind "/etc/sysadmin-app/apuntes" "$home/apuntes"
      if [ $? -eq 0 ]; then
        echo "$home/apuntes mounted successfully"
      fi
    else
      echo "Couldn't remount $home/apuntes, already mounted?"
    fi

    # Process the static site
    if [ "x$(which jekyll)" != "x" ]; then
      if [ -d "$home/public_html/_posts" ]; then
        should_restore_index=0;
        config_file="$home/public_html/build-config.yml"
        if [ -f "$home/public_html/index.jekyll.html" ]; then
          if [ -f "$home/public_html/index.html" ]; then
            should_restore_index=1;
            cp "$home/public_html/index.html" "$home/public_html/index.html.pre_jekyll"
          fi
          cp "$home/public_html/index.jekyll.html" "$home/public_html/index.html"
        fi

        echo "baseurl: \"/~$user/\"" > "$config_file"
        echo "url: \"\"" >> "$config_file"
        cd "$home/public_html"
        jekyll build --config "$home/public_html/_config.yml,$config_file"
        # jekyll build -s "$home/public_html/_posts"           \
        #              -d "$home/public_html/_site"            \
        #              --config "$config_file,$home/public_html/_config.yml" \
        #              --layouts "$home/public_html/_layouts"  \
        #              --plugins "$home/public_html/_plugins"  \
        chown www-data:www-data -R "$home/public_html/_site"
        if [ $should_restore_index -eq 1 ];then
          mv "$home/public_html/index.html.pre_jekyll" "$home/public_html/index.html"
        fi
      # elif [ -d "$home/public_html" ]; then
      #   chown www-data:www-data -R "$home/public_html"
      fi
    else
      echo "jekyll not found, please install it or configure \$PATH!"
    fi
  fi
done

# Find mountpoints of dead users
mounted_dirs=$(mount | grep -e "/home/.*/apuntes" --only-matching)
for directory in $mounted_dirs; do
  username=$(echo "$directory" | cut -d / -f 3);
  if [ "x$username" != "x" ]; then
    # This is just a dumb test to ensure I don't fuck it while testing in my
    # local machine
    if [ "$username" != "emilio" ]; then
      cat /etc/passwd | grep -e "^$username:" > /dev/null 2>&1
      if [ $? -ne 0 ]; then
        if [ -d "/home/$username" ]; then
          # This user no longer exists, unmount the dir and remove it.
          umount "$directory"
          rm -rf "/home/$username"
        fi
      fi
    fi
  fi
done
